# Generated by Django 4.2.5 on 2023-11-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_engine_hours_proximity_ration_delete_categorymodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.IntegerField()),
                ('current_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_liberation', models.BooleanField()),
                ('portions', models.IntegerField()),
                ('food_level', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.DeleteModel(
            name='Proximity',
        ),
        migrations.DeleteModel(
            name='Ration',
        ),
        migrations.AlterField(
            model_name='hours',
            name='times',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='feedtimes',
            name='feed',
            field=models.ManyToManyField(to='api.hours'),
        ),
    ]
