# Generated by Django 4.2.5 on 2023-11-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedtimes_log_delete_engine_delete_proximity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedtimes',
            old_name='feed',
            new_name='feed_time',
        ),
    ]
