# Generated by Django 4.2.5 on 2023-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_feedtimes_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtimes',
            name='feed_time',
            field=models.ManyToManyField(related_name='feed_times', to='api.hours'),
        ),
    ]
