# Generated by Django 4.2.5 on 2023-11-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_feedtimes_feed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtimes',
            name='feed_time',
            field=models.ManyToManyField(to='api.hours'),
        ),
    ]
