# Generated by Django 4.0.6 on 2023-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_feedtimes_feed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='times',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
